services:
  # Create frontend container
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always
    links:
      - backend
  # Create backend container
  backend:  
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: always
    links:
      - db
  # Create database container
  
  db:
    image: mongo
    ports:
    - "5432:5432"
    container_name: database-docker
    restart: always