version: '3'
services:
  # Create frontend container
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    restart: always

  # Create backend container
  backend:  
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  # Create database container
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
