version: '3'
services:

  # Create frontend container
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  # Create backend container
  backend:  
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Create database container
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../data:/data/db
    restart: always
