# Base image
FROM node

RUN npm install -g nodemon

# Set working directory so that all subsequent command runs in this folder
WORKDIR /app

# Copy package json and install dependencies
COPY package*.json ./
RUN npm install

# Copy our app
COPY . .

# Expose port to access server
EXPOSE 8000

# Command to run our app
CMD [ "npm", "run", "dev" ]